### ISSUE TITLE
Passing parameters to get Timezone using Google API module

### ISSUE THREAD

**Issue by MBenoli** [Experience-Monks/google-timezone-api#1]
Hello,

I am new to programmation and I would like to pass the latitude and the longitude as parameters to the timezone to get the result.
I didn't find a solution. Do yo have a solution that I could try?

Thank you,

Sam.

```
function giveTimeZone(lat,lng){
var loc="'"+lat+","+lng+"'";
timezone({
    location: loc
}).then( function( result ) {
    console.log( result );
}).catch( function( err ) {
    console.log( err );
});
}
```

**Comment by mikkoh** [comment]
Hey @MBenoli,

There's no need for the `"'"`. The string your passing to the api would look like `"'43.7182713,-79.3777061'"` when it should be `"43.7182713,-79.3777061"`.

Maybe this will help:

```
function giveTimeZone(lat,lng){
    var loc=lat+","+lng;

    return timezone({
        location: loc
    });
}


// how youd use
giveTimeZone(43.7182713, -79.3777061)
.then( function(result) {
    //received the data
    console.log('do something with result here', result);
})
.catch( function(err) {
    //there was an error somewhere
    throw err;
});
```

Your function should return something most likely so its not bad to just return the promise.

**Comment by MBenoli** [comment]
Thank you very much for your answer!
